bf_code
Startingup2017python1/BFName pull request #1
Opened 2017-10-11 09:05 UTC by gitygity

this is my code. i hope this pull request be correct

2017-10-11 09:50 UTC, masihtehrani commented on bf_code.b
> +[-]
do nothing

2017-10-11 09:52 UTC, masihtehrani requested changes
please change file to your_name+your_family.bf
please write comment for any charachter

2017-10-11 10:57 UTC, masihtehrani requested changes
for one feature use one commit
for change one feature and commit on last commit use
commit --amend

2017-10-17 14:42 UTC, ahangarha approved these changes
The code is working as expected. But I think there are too many loops.

I also passed a test on your code with my unittest on my own script and it passed :+1:

2017-10-19 15:22 UTC, masihtehrani approved these changes
I approve your code,but you are note resolve 2 commit!

2017-10-19 15:23 UTC, merged